### ISSUE TITLE
Empty TOMBSECRET with ZSH 5.3

### ISSUE THREAD

**Issue by popsUlfr** [dyne/Tomb#232]
Hello,

tomb does not work for me, while locking I'm always getting

```
tomb [W] cryptsetup luksFormat returned an error.
```

I found that the TOMBSECRET variable was empty inside the _cryptsetup() : https://github.com/dyne/Tomb/blob/master/tomb#L1055 function and that the problem was happening in gpg_decrypt() : https://github.com/dyne/Tomb/blob/master/tomb#L917

The following gives empty results on GPG 2.1.16 at least
```zsh
TOMBSECRET=`print - "$gpgpass" | \
            gpg --batch --passphrase-fd 0 --no-tty --no-options \
            --status-fd 2 --no-mdc-warning --no-permission-warning \
            --no-secmem-warning` |& grep GNUPG: \
            | read -r -d'\n' gpgstatus
```

The special case for version 1.4.11 does work though

```zsh
TOMBSECRET=`print - "$gpgpass" | \
            gpg --batch --passphrase-fd 0 --no-tty --no-options`
```

This gives me the correct secret that can be passed to cryptsetup.

**Comment by jaromil** [comment]
This is something I'm deeply concerned. We could:
`1` patch this one too investigating what is the specific problem
`2` change the way we use gnupg and switch to assuan commands over gpgagent (but then it requires a daemon running)
`3` use simple openssl aes-256-cbc symmetric encryption in place of gpg
`4` write a simple C program using libcrypto and merging both symmetric encryption and pbkdf2 functions (but then it requires a base binary to be compiled)
While wishing we could have a poll on github I'm wondering what others think.
I am somehow set on having `1` for tomb 2.x series and implement one of the others for tomb 3.x

**Comment by popsUlfr** [comment]
| Gnupg version | State |
| --- | --- | 
| 2.1.15 | not working (1.4.11 case working) |
| 2.1.14 | not working (1.4.11 case working) |
| 2.1.13 | not working (1.4.11 case working) |
| 2.1.12 | not working (1.4.11 case working) |
| 2.1.11 | not working (1.4.11 case working) |
| 2.1.10 | not working (1.4.11 case working) |
| 2.1.9  | not working (1.4.11 case working) |
| 2.1.8  | not working (1.4.11 case working) |
| 2.1.7  | not working (1.4.11 case working) |
| 2.1.6  | not working (1.4.11 case working) |
| 2.1.5  | not working (1.4.11 case working) |
| 2.1.4  | not working (1.4.11 case working) |
| 2.1.3  | not working (1.4.11 case working) |
| 2.1.2  | not working (1.4.11 case working) |
| 2.1.1  | not working (1.4.11 case working) |
| 2.1.0  | not working (1.4.11 case working) |

I'm not going any lower because I don't want to mess up the dependencies.

But the problem lies in the piping, removing :

```bash
 |& grep GNUPG: | read -r -d'\n' gpgstatus
```
works

```bash
TOMBSECRET=`print - "$gpgpass" | \
            gpg --batch --passphrase-fd 0 --no-tty --no-options \
            --status-fd 2 --no-mdc-warning --no-permission-warning \
            --no-secmem-warning`
```

The standard output gets eaten by grep and never lands in TOMBSECRET :(

**Comment by jaromil** [comment]
ACK and thanks for the investigation. Yes please change the title, @parazyd in our crew at dyne has also switched to ZSH 5.3 and noticed irregularities. I dislike the solution suggested by TheConstructor since it implies piping the secret to another process (and binary) while zsh's sysread keeps all in the same memory space.

**Comment by popsUlfr** [comment]
Yes, I see what you mean. I tried a lot of different hacks but every time the stdout gets eaten by the next command, so right now the secret lands in another process any way (grep). I'm not sure if what is happening is actually logical considering that older version of ZSH didn't have that behaviour? Would that be a regression in ZSH or that the old behaviour was wrong?

Looking at this :
```bash
TOMBSECRET=`print - "$gpgpass" | \
            gpg --batch --passphrase-fd 0 --no-tty --no-options \
            --status-fd 2 --no-mdc-warning --no-permission-warning \
            --no-secmem-warning` |& grep GNUPG: \
            | read -r -d'\n' gpgstatus
```

Since the processes are executed in parallel and have their stdin/stdouts connected through pipes it makes more sense to be honest that the 2 streams go through grep, doesn't it?

**Comment by jaromil** [comment]
ZSh 5.3.1 was just released with a bugfix, wondering if this fixes it:
```
You can find version 5.3.1 of zsh at http://www.zsh.org/pub and at
Sorceforge --- except for the gzip version at www.zsh.org, which is slow
arriving.  I'll update the other links if that arrives in time.

The changes from 5.3 are mostly minor; this fixes  "printf -" so it
outputs a "-".

pws
```

**Comment by popsUlfr** [comment]
Hi, same problem with ZSH 5.3.1.

**Comment by jaromil** [comment]
So I tend to think the old behaviour was caused by a bug in ZSh which has been fixed. I remember fiddling quite a lot with that part of the code in Tomb before settling for something that works, at the price of having grep in between....

**Comment by jaromil** [comment]
...just tested can confirm that in ZSh versions >5.3 it works by removing the pipe to grep and read.
I'm still looking for a way so that it works in al cases (which is probably using ASSUAN at last), else we need to isolate the ZSh cases by checking versions.

**Comment by efx** [comment]
@jaromil I can help test a branch against ZSH 5.3 when something is ready.

**Comment by jaromil** [comment]
Please everyone check how it goes with this fix df75c39a584d05eba4f7c575d0b5b650bf2c9b01

All my regression tests passed both with new and old ZSh versions.

**Comment by popsUlfr** [comment]
@jaromil The patch worked with all my tombs

**Comment by Narrat** [comment]
Still getting an error, but I need to check, if I somehow broke something

```
tomb  .  Password OK.
No key available with this passphrase.
tomb [E] Failure mounting the encrypted file.
```

**Comment by jaromil** [comment]
I believe the problem was caused by
1- somehow sloppy implementation (my fault) which could have been better already before the bug
2- a bug in ZSh which was fixed in 5.3.x series that made emerge a fault in my implementation
The current solution I'm proposing does not introduce a special case for ZSh 5.3, rather fixes the implementation and adds security to it by avoiding the use of `grep`. If no problems are reported then I'm incline to release this ASAP. To test is easy just change the interpreter on the first shebang line in `extras/test/runtests` and then use `make` to run it.

**Comment by Narrat** [comment]
I meant to report, that I still cannot open my tombs with tomb from master (with df75c39 included) on zsh-5.3 whereas the same tomb and keyfile work on older versions of tomb and zsh

And something is fishy about the tests. Running it the first time yield a bind fail
Running it again and again (after removing all left overs) leads to this
![1482766987](https://cloud.githubusercontent.com/assets/2787518/21483916/80e72872-cb8a-11e6-89cb-adf8ffb78d2f.png)

and this report
```
7 loop devices busy at start
dig	SUCCESS
forge	SUCCESS
lock	SUCCESS
badpass	FAIL
open	SUCCESS
close	FAIL
passwd	SUCCESS
chksum	SUCCESS
bind	FAIL
setkey	SUCCESS
resize	FAIL
14 loop devices busy at end

```

**Comment by popsUlfr** [comment]
The patch works for me but the tests go bonkers

```
16 loop devices busy at start
dig     SUCCESS
forge   SUCCESS
lock    SUCCESS
badpass FAIL
open    SUCCESS
close   FAIL
passwd  SUCCESS
chksum  SUCCESS
bind    SUCCESS
setkey  SUCCESS
resize  FAIL
kdforge SUCCESS
kdfpass SUCCESS
kdflock SUCCESS
kdfopen SUCCESS
stgin   SUCCESS
stgout  SUCCESS
stgopen SUCCESS
stgpipe SUCCESS
stgimpl SUCCESS
qrenc   SUCCESS
26 loop devices busy at end
```

None of my tombs were mounted before running the tests.

I get a lot of these:

```
rmdir: failed to remove '/media/test': Device or resource busy
device-mapper: remove ioctl on tomb.test.1482766977.loop16 failed: Device or resource busy
...
Device tomb.test.1482766977.loop16 is still in use.
tomb [E] Error occurred in cryptsetup luksClose tomb.test.1482766977.loop16
     Tomb command returns 1
```

**Comment by jaromil** [comment]
There seems to be something very strange with the unmounting of loop devices on the system you ran these tests. See here an example run on latest HEAD using ubuntu 14 with older ZSh https://travis-ci.org/dyne/Tomb

**Comment by parazyd** [comment]
Same test results like @popsUlfr here with zsh 5.3.

**Comment by popsUlfr** [comment]
@parazyd Indeed, the tests leave quite a mess. LuksClose isn't getting called so the loop devices are still in use.

```bash
$ ls -1 /dev/mapper/
tomb.test.1482767889.loop0
tomb.test.1482767894.loop1
tomb.test.1482767903.loop2
tomb.test.1482767911.loop3
tomb.test.1482767919.loop4
tomb.test.1482767927.loop5
tomb.test.1482767945.loop6
tomb.test.1482767971.loop7
tomb.test.1482767978.loop8
tomb.test.1482767986.loop9
```

**Comment by parazyd** [comment]
`cryptsetup luksClose` is getting called. Otherwise you couldn't close your normal tombs. It's only the first tomb opened by the test unit that's causing problems.

**Comment by jaromil** [comment]
New CI build based on Arch userland in a Travis chroot https://travis-ci.org/dyne/Tomb/builds/186801746

But I still cannot reproduce your problem.

**Comment by Narrat** [comment]
One problem is the generation of 
```
tomb  .  Commanded to dig tomb /media/test/datacheck.raw
```
Without udisks installed, /media won't exist, if the user didn't create it manually

**Comment by jaromil** [comment]
ACK. This may be a test-suite specific error then.
`datacheck.raw` is just a random file that is then checksummed to test integrity of preservation: the dig command is just used because is handy, not to create another tomb inside a tomb.
The datacheck.raw file is created inside the monted `test` tomb. Here below the code handling the default mountpoint for tombs when not specified:
```shell
    tombmount="$2"
    [[ "$tombmount" = "" ]] && {
        tombmount=/media/$TOMBNAME
        [[ -d /media ]] || { # no /media found, adopting /run/media/$USER (udisks2 compat)
            tombmount=/run/media/$_USER/$TOMBNAME
        }
        _message "Mountpoint not specified, using default: ::1 mount point::" $tombmount
    }
```
Where is test.tomb mounted then on your system?

**Comment by popsUlfr** [comment]
@parazyd I mean during the tests luksClose just fails whereas doing it manually afterwards works. Could it be a race condition somewhere? Why is umount exiting without errors but the folder is still busy and rmdir fails?

**Comment by parazyd** [comment]
@popsUlfr Don't type the correct password when the test unit asks you for one.

**Comment by Narrat** [comment]
hmm.. the main reason why the test is failing, happens on "Testing open with wrong password" if the right password is entered.
Entering whatever leads to a clean end, but entering test there.. well

**Comment by jaromil** [comment]
ok that was it. yes that test exists to check that when the wrong password is entered then tomb quits closing all correctly and signaling the error. The wrong password needs to be typed or can also safely wait for timeout. Was that it?

**Comment by jaromil** [comment]
This reminds me of a rather important item on my TODO for Tomb, which is to avoid mounting twice the same tomb. There must be a check if the tomb is already mounted then abort mounting it again, which is what happens in the tests if the right password is inserted at the wrong-password-check.

**Comment by popsUlfr** [comment]
I'm confused, what is the right password supposed to be? When it asked I just typed 'test' I assumed it asked me to set the password? After the first password prompt it didn't ask me again.

**Comment by jaromil** [comment]
the problem is that you typed 'test' :^) one should just press enter or wait timeout on the "wrong password test".

**Comment by popsUlfr** [comment]
Yeah I was very confused haha, sorry for that. All tests go through, it's all good

```
tomb (*) Test results summary

0 loop devices busy at start
dig     SUCCESS
forge   SUCCESS
lock    SUCCESS
badpass SUCCESS
open    SUCCESS
close   SUCCESS
passwd  SUCCESS
chksum  SUCCESS
bind    SUCCESS
setkey  SUCCESS
resize  SUCCESS
kdforge SUCCESS
kdfpass SUCCESS
kdflock SUCCESS
kdfopen SUCCESS
stgin   SUCCESS
stgout  SUCCESS
stgopen SUCCESS
stgpipe SUCCESS
stgimpl SUCCESS
qrenc   SUCCESS
0 loop devices busy at end
```

**Comment by jaromil** [comment]
Thanks everyone!

**Comment by Narrat** [comment]
And I'm just going to create a new tomb and copy contents over, as I cannot figure out why the stuff is failing for my old tomb
1) Old tomb, fails to open
2) Old tomb opens fine on old zsh and older tomb build
3) Creating new tomb and locking with old keyfile works fine

**Comment by jaromil** [comment]
Narrat: wait, keep it as it is an important corner case for regression. Can you tell what ZSh and GnuPG versions are you running? what is tomb's log when run with `-D` (`DEBUG=1`)
Please note latest commit improves also debug log messages on failed open.

**Comment by Narrat** [comment]
ZSh 5.3.1
GnuPG 2.1.17

```
tomb [D] Identified caller: omnius (1000:100)
tomb [D] Tomb command: open <Tomb_to_open>
tomb [D] Caller: uid[1000], gid[100], tty[/dev/pts/4].
tomb [D] Temporary directory: /tmp/zsh
tomb  .  Commanded to open tomb <Tomb_to_open>
tomb [D] is_valid_tomb <Tomb_to_open>
tomb  .  Valid tomb file found: <Tomb_to_open>
tomb [D] load_key argument: <Keypath>
tomb [D] load_key: <Keypath>
tomb [D] is_valid_key
tomb  .  Key is valid.
tomb  .  Mountpoint not specified, using default: /run/media/omnius/<Tomb_to_open>
tomb (*) Opening <Tomb_to_open> on /run/media/omnius/<Tomb_to_open>
tomb  .  This tomb is a valid LUKS encrypted device.
tomb  .  Cipher is "aes" mode "xts-plain64:sha256" hash "sha1"
tomb [D] dev mapper device: tomb.<Tomb_to_open>.1482771973.loop0
tomb [D] Tomb key: <Keypath>
tomb [D] Tomb name: <Tomb_to_open> (to be engraved)
tomb  .  A password is required to use key <Keypath>
tomb [D] asking password with tty=/dev/pts/4 lc-ctype=C
tomb [D] using pinentry-gtk2
tomb [D] get_lukskey
tomb [D] Created tempfile: /tmp/zsh/2266716127440827946
tomb [D] gpg: AES256 encrypted data
tomb [D] [GNUPG:] NEED_PASSPHRASE_SYM 9 3 2
tomb [D] gpg: encrypted with 1 passphrase
tomb [D] [GNUPG:] BEGIN_DECRYPTION
tomb [D] [GNUPG:] DECRYPTION_INFO 2 9
tomb [D] [GNUPG:] DECRYPTION_FAILED
tomb [D] gpg: decryption failed: Bad session key
tomb [D] [GNUPG:] END_DECRYPTION
tomb [D] get_lukskey returns 1
tomb [D] asking password with tty=/dev/pts/4 lc-ctype=C
tomb [D] using pinentry-gtk2
tomb [D] get_lukskey
tomb [D] Created tempfile: /tmp/zsh/3204928802385910479
tomb [D] gpg: AES256 encrypted data
tomb [D] [GNUPG:] NEED_PASSPHRASE_SYM 9 3 2
tomb [D] gpg: encrypted with 1 passphrase
tomb [D] [GNUPG:] BEGIN_DECRYPTION
tomb [D] [GNUPG:] DECRYPTION_INFO 2 9
tomb [D] [GNUPG:] PLAINTEXT 62 1409354956 tomb.tmp
tomb [D] [GNUPG:] PLAINTEXT_LENGTH 256
tomb [D] [GNUPG:] DECRYPTION_OKAY
tomb [D] [GNUPG:] GOODMDC
tomb [D] [GNUPG:] END_DECRYPTION
tomb [D] get_lukskey returns 0
tomb  .  Password OK.
No key available with this passphrase.
tomb [E] Failure mounting the encrypted file.
```

(The first failure (gpg: decryption failure) resulting from entering the wrong password)

**Comment by jaromil** [comment]
This may be related to issue #226. Let us know if you time more time to investigate this case. You may have to analyse the decoded secret data of the key with `hexdump` then obviously posting here is not an option...

**Comment by jaromil** [comment]
I have added full regression tests against older Tomb 2.x stable releases and they are all passed by current HEAD, this is now also visible on Travis https://travis-ci.org/dyne/Tomb/builds/186826105

This test now rules out the possible bug on keys mentioned above: that is not a bug for Tomb, but it can be for third-party tool compatibility and @mhogomchungu is right in mentioning "its ugly". I'm going to fix it in the next commit on master.
However, about your very problem, I have no idea anymore about what can be causing it. It may be not strictly related to Tomb...

**Comment by Narrat** [comment]
This specific tomb and keyfile should be from 1.x releases, but that shouldn't propably make a difference.
And I can tell, the story gets even weirder.
I upgraded tomb again to latest master, and again, couldn't open the newly created tomb (using the old keyfile). Did go back to the previous build and can open the tomb again. And that totally doesn't make sense.
Well.. Now I will create a new keyfile and we will see what happens then

**Comment by jaromil** [comment]
WOW. OK so in your case lets say we have a `magic key`, an `old tomb` and a `new tomb`, both locked with this `magic key` created with 1.x. Then the cases below, please correct me if wrong:
1. `new tomb` opens with 2.2
2. `new tomb` does not open with current HEAD
3. `old tomb` opens with 2.2
4. `old tomb` opens with current HEAD
Question: what did you used to lock `new tomb` with `magic key`? 2.2 or current HEAD?
ACK for the ZSh 5.3 issue. Will close this soon, however I am interested to isolate your issue. If you created `new tomb` with a commit between 2.2 and current HEAD then I may have an idea about it.

**Comment by Narrat** [comment]
Didn't test new tomb with old tomb version, but yes, the other cases are right.
Or it could be added, that old tomb inbetween 2.2 and current HEAD couldn't be opened

The new tomb was created and locked with tomb build based on commit df75c39.

For the tests, I downgraded ZSh back to 5.2, else I would fail with tomb-2.2
Test files:
2x tombs created with tomb from latest HEAD (14cba81), 1 locked with magic key, 1 with a key from tomb based on HEAD
2x tombs created with tomb 2.2, one locked with the magic key and one with the new.

tomb 2.2 could open tomb created from latest-HEAD-tomb and the newly forged key, as well with the old key
tomb from HEAD could open the tombs created with tomb 2.2 (old and new key)

Using tomb@df75c39 I could open the tombs created by latest-HEAD-tomb only if using the new key. Open with the tomb locked with the old key failed.
The same case, with the tombs created by tomb-2.2
They one using the key created from latest-HEAD-tomb could be opened, but not the one with the old key.

**Comment by jaromil** [comment]
More or less it does, thanks for the detail.
I need to sleep over this, however it looks like current HEAD solves all problems and most importantly the ZSh 5.3 issue on topic. Commit db976a521029c5991d8316f6d0572e5d6e9b482e may indeed be relevant to your issue.

**Comment by efx** [comment]
@jaromil thank you for the fix! verified HEAD (14cba81) correctly opens my tomb.
gpg (GnuPG) 2.1.17
zsh 5.3.1

**Comment by tomw1982** [comment]
Hi, maybe I`m not very advanced linux user, I`m using few year but I recompile all things related with tomb, now I have tomb - version 2.1, zsh - version 5.1 and gnupg - version 2.1.13 from 14.06.2016 and I still have problem with opening tomb. This same all time: $ tomb open priv.tomb -k priv.tomb.key -f
tomb  .  Commanded to open tomb priv.tomb
tomb  .  Valid tomb file found: priv.tomb
tomb  .  Key is valid.
tomb  .  Mountpoint not specified, using default: /run/media/tomasz/priv
tomb (*) Opening priv on /run/media/tomasz/priv

[sudo] Enter password for user tomasz to gain superuser privileges


tomb  .  This tomb is a valid LUKS encrypted device.
tomb  .  Cipher is "aes" mode "xts-plain64:sha256" hash "sha1"
tomb  .  A password is required to use key priv.tomb.key

(pinentry-gtk-2:28980): Gtk-WARNING **: Nie można odnaleźć modułu obsługującego motyw w module_path: "adwaita",

(pinentry-gtk-2:28980): Gtk-WARNING **: Nie można odnaleźć modułu obsługującego motyw w module_path: "adwaita",

** (pinentry-gtk-2:28980): WARNING **: it took 190 tries to grab the keyboard
tomb  .  Password OK.
tomb [E] Failure mounting the encrypted file.

I dont know how to fix this. Can anybody help me?

**Comment by jaromil** [comment]
This seems to not be related with this bug. I am afraid it may be due to tomb file corruption.
The error you are getting is due to cryptsetup returning non-zero. You can debug it more in-deep by running the manual command to open a tomb (the same one suggested in the README section "How secure is this?") and eventually adding more debugging flags to `cryptsetup` if it allows it. The command sequence is this:
```
lo=$(losetup -f)
losetup -f secret.tomb
pass="$(gpg -d secret.key)"
echo -n -e "$pass" | cryptsetup --key-file - luksOpen $lo secret
mount /dev/mapper/secret /mnt
```
I will now close this issue as its subject is solved. I sincerely hope you solve your issue and if it relates to how tomb is written then please do not hesitate to file another more specific issue. Best wishes

**Comment by jaromil** [comment]
for instance a good try can be to do `echo $?` right after the cryptsetup command, then see what the error code is and compare it to the narrow list that cryptsetup manpage gives in its `RETURN CODES` section.
```
 Error codes are: 1 wrong parameters, 2 no permission (bad passphrase), 3 out of memory, 4 wrong device specified, 5 device  already  exists or device is busy.
```
We shall include that error code in our error message indeed.
