### ISSUE TITLE
permission denied error for hook files on initial opening

### ISSUE THREAD

**Issue by encodeering** [dyne/Tomb#312]
Hi,

I have created a user `sentry` with the following sudoers entry
```
cat /etc/sudoers.d/sentry
sentry ALL=(ALL) NOPASSWD:ALL
```

When I try to open the tomb file the first time, the following log occurs and no files are written

```
tomb (*) Success opening tomb on /media/tomb
_update_control_file:7: permission denied: /media/tomb/.uid
chown: /media/tomb/.uid: No such file or directory
tomb [D] updated control file /media/tomb/.uid = 1000
_update_control_file:7: permission denied: /media/tomb/.tty
chown: /media/tomb/.tty: No such file or directory
tomb [D] updated control file /media/tomb/.tty = /dev/pts/0
_update_control_file:7: permission denied: /media/tomb/.host
chown: /media/tomb/.host: No such file or directory
tomb [D] updated control file /media/tomb/.host = 0b3ce6917f5d
_update_control_file:7: permission denied: /media/tomb/.last
chown: /media/tomb/.last: No such file or directory
tomb [D] updated control file /media/tomb/.last = 1523698216
tomb [D] bind-hooks not found in /media/tomb
```

```
ls -la /media/tomb/
total 17
drwxr-xr-x    3 sentry   sentry        1024 Apr 14 09:30 .
drwxr-xr-x    1 sentry   sentry        4096 Apr 14 09:30 ..
drwx------    2 sentry   sentry       12288 Apr 14 09:30 lost+found
```

The error doesn't occur is I close and reopen the tomb afterwards

```
tomb (*) Success opening tomb on /media/tomb
tomb [D] updated control file /media/tomb/.uid = 1000
tomb [D] updated control file /media/tomb/.tty = /dev/pts/0
tomb [D] updated control file /media/tomb/.host = 0b3ce6917f5d
tomb [D] updated control file /media/tomb/.last = 1523698596
```

```
ls -la /media/tomb/
total 21
drwxr-xr-x    3 sentry   sentry        1024 Apr 14 09:36 .
drwxr-xr-x    1 sentry   sentry        4096 Apr 14 09:36 ..
-rw-------    1 sentry   sentry          13 Apr 14 09:36 .host
-rw-------    1 sentry   sentry          11 Apr 14 09:36 .last
-rw-------    1 sentry   sentry          11 Apr 14 09:36 .tty
-rw-------    1 sentry   sentry           5 Apr 14 09:36 .uid
drwx------    2 sentry   sentry       12288 Apr 14 09:30 lost+found
```

The logs seem to be non-critical, but they look a bit scary in the first place. I've already tried to change the ownership of `/media`, but without success. Am I doing something wrong?

Cheers

**Comment by encodeering** [comment]
```
tomb -v
  Tomb 2.5 - a strong and gentle undertaker for your secrets

   Copyright (C) 2007-2017 Dyne.org Foundation, License GNU GPL v3+
   This is free software: you are free to change and redistribute it
   For the latest sourcecode go to <http://dyne.org/software/tomb>

   This source code is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
   When in need please refer to <http://dyne.org/support>.

  System utils:

  Sudo version 1.8.21p2
  cryptsetup 1.7.5
  pinentry-curses (pinentry) 1.0.0
Copyright (C) 2016 g10 Code GmbH
License GPLv2+: GNU GPL version 2 or later <https://www.gnu.org/licenses/>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
  findmnt from util-linux 2.31
  gpg (GnuPG) 2.2.3 - key forging algorithms (GnuPG symmetric ciphers):
  /usr/bin/gpg
 IDEA 3DES CAST5 BLOWFISH AES AES192 AES256 TWOFISH CAMELLIA128 CAMELLIA192 CAMELLIA256

  Optional utils:

  /usr/bin/gettext
  dcfldd not found
  /usr/bin/shred
  /usr/bin/steghide
  /usr/sbin/resize2fs
  tomb-kdb-pbkdf2 not found
  /usr/bin/qrencode
  swish-e not found
  unoconv not found
  /usr/bin/lsof
```

**Comment by jaromil** [comment]
Yes, indeed should be fixed in master. This calls for a new release perhaps. Meanwhile everyone is welcome and encouraged to try reproduce with current git HEAD and confirm the fix.

**Comment by encodeering** [comment]
I have checked `8d698ad46aa11d45880d2bc00f2d631608fe46a6` and it turns out, that I can still see the warning if I skip `sudo` and in case of `sudo`, the message is like this:

```
tomb [W] Pinentry error: Permission
tomb [W] User aborted password dialog.
tomb [E] No valid password supplied.
```

However, it seems to happen only, if I switch to `sentry` by Docker's `USER` build directive, but not if I run the container with `root` and switch to `sentry` manually. In the latter case I *have* to use `sudo`.

So it might not be related to tomb, but maybe you know what it could be.
Sorry, forgot to mention that I want to use tomb inside of docker, but didn't thought it would make a huge difference.

Cheers

**Comment by jaromil** [comment]
ACK. Facilitating the use of Tomb inside Docker is definitely a nice feature (especially considering cross-platform usage beyond Linux) so I'll try to reproduce this following the above information and see what can be done.

**Comment by jaromil** [comment]
orginal issue was solved, support for docker is documented elsewhere.
