### ISSUE TITLE
Avoid mounting same tomb twice or on already used mountpoints

### ISSUE THREAD

**Issue by stevelitt** [dyne/Tomb#326]
When the user makes the mistake of running tomb open multiple times,  it is allowed. Each extra open performs the mount on top of the last mount point, masking it. Each extra open creates an extra /dev/mapper/tombname.tomb.number.loopDigit. tomb list lists all of them, but on all but one says they're not available because they're masked by another tomb.

There's no pure Tomb way out of this. You can repeatedly perform sudo tomb close tombname until it reports no tombs open, but /dev/mapper still contains the extra loops. Those are gotten rid of only by repeatedly performing cryptsetup close tombname.tomb.*

Would it be better if Tomb immediately check the eventual mountpoint pathname for existance, and refuse to act if it is: Hopefully with an informative error message.

This isn't a bug, because the cause is user error. But the user making the error is presented with a very difficult situation, so maybe a barrier should be erected to prevent it.

**Comment by jaromil** [comment]
Good point, some time in the past I thought we fixed this (refusing to mount the same tomb twice) but perhaps I've overlooked it. Should be an easy fix.

**Comment by amerlyq** [comment]
Problem still exists and it's not minor but major one :(
Look here for bug description and consequences:
https://github.com/roddhjav/pass-tomb/issues/27
It's a pity, but I couldn't debug the problem root cause by my own limited ability to provide a fix.
P.S. I will copy issue description here too if you request it.
